---

- hosts: all
  tasks:

  - name: install apache2 and php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes  
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php for Fedora
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes     
    when: ansible_distribution == "Fedora"    
