---

- hosts: all
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: update,ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"    

  - name: install updates (Fedora)
    tags: update,fedora
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

- hosts: all
  roles: 
    - base

- hosts: web_servers
  roles:
    - web_servers

- hosts: db_servers
  roles:
    - db_servers  
