---

- hosts: all
  tasks:

  - name: cleanup (Ubuntu)
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - mariadb-server  
      state: absent
    when: ansible_distribution == "Ubuntu"    

  - name: cleanup (Fedora)
    dnf:
      name:
        - httpd
        - php
        - mariadb  
      state: absent
    when: ansible_distribution == "Fedora"
