- name: cleanup
  tags: apache
  package:
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: absent

- name: install apache
  tags: apache
  package:
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: copy default html file for apache
  tags: apache
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644  

- name: start apache (Ubuntu)
  tags: apache,ubuntu
  command: service apache2 start
  when: ansible_distribution == "Ubuntu"
