- name: cleanup (Ubuntu)
  apt:
    name: 
      - apache2
      - libapache2-mod-php
    state: absent
  when: ansible_distribution == "Ubuntu"

- name: cleanup (Fedora)
  dnf:
    name:
      - httpd
      - php
    state: absent
  when: ansible_distribution == "Fedora"  

- name: install apache (Ubuntu)
  tags: apache,ubuntu
  apt:
    name: 
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache (Fedora)
  tags: apache,fedora
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "Fedora"

- name: copy default html file for apache
  tags: apache
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644  

- name: start apache (Ubuntu)
  tags: apache,ubuntu
  command: service apache2 start
  when: ansible_distribution == "Ubuntu"
