- name: check installed Java version
  tags: java
  shell: java -version
  register: current_java_version
  ignore_errors: yes # avoid failure if Java is not installed  
  
- name: display current Java version
  tags: java
  debug:
    msg: "{{ current_java_version.stderr_lines | default([]) }}"

- name: Find installed Java package (Ubuntu)
  tags: java
  shell: dpkg --list | grep openjdk | awk '{print $2}' | sed 's/:amd64$//'
  register: installed_java_package_ubuntu
  changed_when: false
  when: ansible_distribution == "Ubuntu"    

- name: Find installed Java package (Fedora)
  tags: java
  shell: rpm -qa | grep openjdk
  register: installed_java_package_fedora
  changed_when: false
  when: ansible_distribution == "Fedora"

- name: Uninstall current Java version (if found)
  tags: java
  package:
    name: "{{ (installed_java_package_ubuntu.stdout_lines | default([])) + (installed_java_package_fedora.stdout_lines | default([])) }}"
    state: absent
  when: >
    (installed_java_package_ubuntu.stdout_lines is defined and installed_java_package_ubuntu.stdout_lines | length > 0) or
    (installed_java_package_fedora.stdout_lines is defined and installed_java_package_fedora.stdout_lines | length > 0)

- name: install the desired Java version
  tags: java
  package: 
    name: "{{ java_package_name }}"
    state: present

- name: verify newly installed Java version
  tags: java
  shell: java -version
  register: new_java_version
  ignore_errors: yes

- name: display Java version
  debug:
    msg: "{{ new_java_version.stderr_lines }}"  
