---

- hosts: all
  tasks:

  - name: remove apache2 on Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php  
      state: absent
    when: ansible_distribution == "Ubuntu"    

  - name: remove httpd on Fedora
    dnf:
      name:
        - httpd
        - php
      state: absent
    when: ansible_distribution == "Fedora"    
