- name: cleanup
  tags: db
  package:
    name: "{{ mariadb_package_name }}"  
    state: absent

- name: install mariadb
  tags: db
  package:
    name: "{{ mariadb_package_name }}"
    state: latest

- name: start mariadb (Ubuntu)
  tags: db,ubuntu
  shell: nohup mariadbd --user=root --skip-networking=0 --socket=/run/mysqld/mysqld.sock > /dev/null 2>&1 &  
  when: ansible_distribution == "Ubuntu"    
